SERVER_IP = "127.0.0.1"
SERVER_PORT = "8080"
SERVER_URL = "http://" + SERVER_IP + ":" + SERVER_PORT
SERVER_UPLOAD_SUFFIX = "/upload"
SERVER_UPLOAD_URL = SERVER_URL + SERVER_UPLOAD_SUFFIX

FILE_UPLOAD_FIELD_NAME = "upload_file"

NUKE_SAVED_FILES_ON_STARTUP = True
REALLY_NUKE_SAVED_FILES_ON_STARTUP = True
