SERVER_URL           = "http://localhost:8080"
SERVER_UPLOAD_SUFFIX = "/upload"
SERVER_UPLOAD_URL    = SERVER_URL + SERVER_UPLOAD_SUFFIX

FILE_UPLOAD_FIELD_NAME = "upload_file"

NUKE_SAVED_FILES_ON_STARTUP        = True
REALLY_NUKE_SAVED_FILES_ON_STARTUP = True

SHOW_COLORED_LOGS = False
